package edu.fudan.common.client.dto.train;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Data transfer object for train type definitions.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class TrainTypeDto {

    /**
     * Unique identifier generated by the train service.
     */
    private String id;

    /**
     * Display name of the train type (e.g., G-series).
     */
    private String name;

    /**
     * Available seats in economy class.
     */
    private Integer economyClass;

    /**
     * Available seats in comfort class.
     */
    private Integer confortClass;

    /**
     * The average speed for this train type in km/h.
     */
    private Integer averageSpeed;
}
