# coding: utf-8

"""
    Voucher Service API

    API documentation for the Train Ticket Voucher microservice. This service provides an endpoint for retrieving or generating reimbursement vouchers based on order information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class VoucherDto(BaseModel):
    """
    Voucher information data transfer object.
    """ # noqa: E501
    voucher_id: StrictInt = Field(description="Primary key of voucher record.", alias="voucherId")
    order_id: StrictStr = Field(description="Order id to which this voucher is bound.", alias="orderId")
    travel_date: date = Field(description="Travel date in yyyy-MM-dd format.", alias="travelDate")
    travel_time: StrictStr = Field(description="Travel time string, e.g. \"08:30\".", alias="travelTime")
    contact_name: StrictStr = Field(description="Contact person name.", alias="contactName")
    train_number: StrictStr = Field(description="Train number, e.g. \"G1234\".", alias="trainNumber")
    seat_class: StrictInt = Field(description="Seat class code, aligns with order-service seatClass.", alias="seatClass")
    seat_number: StrictStr = Field(description="Seat number string.", alias="seatNumber")
    start_station: StrictStr = Field(description="Departure station.", alias="startStation")
    dest_station: StrictStr = Field(description="Destination station.", alias="destStation")
    price: Union[StrictFloat, StrictInt] = Field(description="Ticket price.")
    __properties: ClassVar[List[str]] = ["voucherId", "orderId", "travelDate", "travelTime", "contactName", "trainNumber", "seatClass", "seatNumber", "startStation", "destStation", "price"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of VoucherDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of VoucherDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "voucherId": obj.get("voucherId"),
            "orderId": obj.get("orderId"),
            "travelDate": obj.get("travelDate"),
            "travelTime": obj.get("travelTime"),
            "contactName": obj.get("contactName"),
            "trainNumber": obj.get("trainNumber"),
            "seatClass": obj.get("seatClass"),
            "seatNumber": obj.get("seatNumber"),
            "startStation": obj.get("startStation"),
            "destStation": obj.get("destStation"),
            "price": obj.get("price")
        })
        return _obj


