server:
  port: 18855

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:127.0.0.1:8848}
  application:
    name: ts-food-merchant-service
  datasource:
#    url: jdbc:mysql://localhost:3306/ts-food-merchant-mysql?useSSL=false
    url: jdbc:mysql://${FOOD_MERCHANT_MYSQL_HOST:10.176.122.1}:${FOOD_MERCHANT_MYSQL_PORT:3306}/${FOOD_MERCHANT_MYSQL_DATABASE:ts}?useSSL=false
    username: ${FOOD_MERCHANT_MYSQL_USER:root}
    password: ${FOOD_MERCHANT_MYSQL_PASSWORD:Abcd1234#}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

swagger:
  controllerPackage: food.controller