package edu.fudan.common.client.dto.station;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Station data transfer object mirroring the station service entity.
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class StationDto {

    /**
     * Unique identifier generated by the station service.
     */
    private String id;

    /**
     * Lowercase, whitespace-stripped station name.
     */
    private String name;

    /**
     * Planned stay time (in minutes) for trains at this station.
     */
    private int stayTime;
}

