# HTTP Server
server:
  port: 18888  # HTTP (Tomcat) port

spring:
  main:
    web-application-type: reactive
  application:
    name: ts-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:127.0.0.1:8848}
    gateway:
      routes:
        - id: auth
          uri: lb://${AUTH_SERVICE_HOST:ts-auth-service}
          predicates:
            - Path=/api/v1/auth/**

        - id: auth-user
          uri: lb://${AUTH_SERVICE_HOST:ts-auth-service}
          predicates:
            - Path=/api/v1/users/**

        - id: verifycode
          uri: lb://${AUTH_SERVICE_HOST:ts-auth-service}
          predicates:
            - Path=/api/v1/verifycode/**

        - id: avatar
          uri: lb://${AVATAR_SERVICE_HOST:ts-avatar-service}
          predicates:
            - Path=/api/v1/avatar/**

        - id: basic
          uri: lb://${BASIC_SERVICE_HOST:ts-basic-service}
          predicates:
            - Path=/api/v1/basicservice/**

        - id: config
          uri: lb://${CONFIG_SERVICE_HOST:ts-config-service}
          predicates:
            - Path=/api/v1/configservice/**

        - id: consign
          uri: lb://${CONSIGN_SERVICE_HOST:ts-consign-service}
          predicates:
            - Path=/api/v1/consignservice/**

        - id: contacts
          uri: lb://${CONTACTS_SERVICE_HOST:ts-contacts-service}
          predicates:
            - Path=/api/v1/contactservice/**

        - id: execute
          uri: lb://${EXECUTE_SERVICE_HOST:ts-execute-service}
          predicates:
            - Path=/api/v1/executeservice/**

        - id: food
          uri: lb://${FOOD_SERVICE_HOST:ts-food-booking-service}
          predicates:
            - Path=/api/v1/foodbooking/**

        - id: inside-payment
          uri: lb://${INSIDE_PAYMENT_SERVICE_HOST:ts-inside-payment-service}
          predicates:
            - Path=/api/v1/inside_pay_service/**

        - id: user-notification
          uri: lb://${USER_NOTIFICATION_SERVICE_HOST:ts-user-notification-service}
          predicates:
            - Path=/api/v1/user-notification/**

        - id: order
          uri: lb://${ORDER_SERVICE_HOST:ts-order-service}
          predicates:
            - Path=/api/v1/orderservice/**

        - id: order-query
          uri: lb://${ORDER_QUERY_SERVICE_HOST:ts-order-query-service}
          predicates:
            - Path=/api/v1/order-query/**

        - id: payment
          uri: lb://${PAYMENT_SERVICE_HOST:ts-payment-service}
          predicates:
            - Path=/api/v1/paymentservice/**

        - id: ticket-purchase
          uri: lb://${TICKET_PURCHASE_SERVICE_HOST:ts-ticket-purchase-service}
          predicates:
            - Path=/api/v1/preserveservice/**

        - id: price
          uri: lb://${TICKET_SERVICE_HOST:ts-ticket-service}
          predicates:
            - Path=/api/v1/ticket/**

        - id: route
          uri: lb://${ROUTE_PLAN_SERVICE_HOST:ts-route-plan-service}
          predicates:
            - Path=/api/v1/routeservice/**

        - id: security
          uri: lb://${SECURITY_SERVICE_HOST:ts-security-service}
          predicates:
            - Path=/api/v1/securityservice/**

        - id: station
          uri: lb://${STATION_SERVICE_HOST:ts-station-service}
          predicates:
            - Path=/api/v1/stationservice/**

        - id: food-list
          uri: lb://${FOOD_LIST_SERVICE_HOST:ts-food-list-service}
          predicates:
            - Path=/api/v1/foodlist/**

        - id: ticket-plan
          uri: lb://${TICKET_PLAN_SERVICE_HOST:ts-ticket-plan-service}
          predicates:
            - Path=/api/v1/ticketplan/**

        - id: travel
          uri: lb://${TRAVEL_SERVICE_HOST:ts-ticket-query-service}
          predicates:
            - Path=/api/v1/ticketquery/**

        - id: user
          uri: lb://${USER_SERVICE_HOST:ts-user-service}
          predicates:
            - Path=/api/v1/userservice/users/**
