apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: trainticket-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: trainticket
spec:
  hosts:
  - "*"
  gateways:
  - trainticket-gateway
  http:
  - match:
    - uri:
        exact: /
    - uri:
        exact: /old_index.html
    - uri:
        exact: /index.html
    - uri:
        exact: /client_ticket_collect.html
    - uri:
        exact: /client_ticket_book.html
    - uri:
        exact: /client_order_list.html
    - uri:
        exact: /client_login.html
    - uri:
        exact: /client_enter_station.html
    - uri:
        exact: /client_consign_list.html
    - uri:
        exact: /client_adsearch.html
    - uri:
        exact: /voucher.html
    - uri:
        exact: /adminlogin.html
    - uri:
        exact: /admin_user.html
    - uri:
        exact: /admin_travel.html
    - uri:
        exact: /admin_train.html
    - uri:
        exact: /admin_station.html
    - uri:
        exact: /admin_route.html
    - uri:
        exact: /admin_price.html
    - uri:
        exact: /admin_contacts.html
    - uri:
        exact: /admin_config.html
    - uri:
        exact: /admin.html
    - uri:
        exact: /add&delete.html
    - uri:
        prefix: /js/
    - uri:
        prefix: /css/
    - uri:
        prefix: /assets/
    route:
    - destination:
        host: ts-ui-dashboard
        port:
          number: 8080
  
  - match:
    - uri:
        prefix: /api/v1/auth
    route:
    - destination:
        host: ts-auth-service
        port:
          number: 12340

  - match:
    - uri:
        prefix: /api/v1/avatar
    route:
    - destination:
        host: ts-avatar-service
        port:
          number: 17001

  - match:
    - uri:
        prefix: /api/v1/basic
    route:
    - destination:
        host: ts-basic-service
        port:
          number: 15680

  - match:
    - uri:
        prefix: /api/v1/config
    route:
    - destination:
        host: ts-config-service
        port:
          number: 15679

  - match:
    - uri:
        prefix: /api/v1/consign
    route:
    - destination:
        host: ts-consign-service
        port:
          number: 16111

  - match:
    - uri:
        prefix: /api/v1/contact
    route:
    - destination:
        host: ts-contacts-service
        port:
          number: 12347

  - match:
    - uri:
        prefix: /api/v1/delivery
    route:
    - destination:
        host: ts-delivery-service
        port:
          number: 18808

  - match:
    - uri:
        prefix: /api/v1/execute
    route:
    - destination:
        host: ts-execute-service
        port:
          number: 12386

  - match:
    - uri:
        prefix: /api/v1/food-booking
    route:
    - destination:
        host: ts-food-booking-service
        port:
          number: 18856

  - match:
    - uri:
        prefix: /api/v1/food-delivery
    route:
    - destination:
        host: ts-food-delivery-service
        port:
          number: 18957

  - match:
    - uri:
        prefix: /api/v1/food-list
    route:
    - destination:
        host: ts-food-list-service
        port:
          number: 19998

  - match:
    - uri:
        prefix: /api/v1/food-merchant
    route:
    - destination:
        host: ts-food-merchant-service
        port:
          number: 18855

  - match:
    - uri:
        prefix: /api/v1/inside-payment
    route:
    - destination:
        host: ts-inside-payment-service
        port:
          number: 18673

  - match:
    - uri:
        prefix: /api/v1/order-query
    route:
    - destination:
        host: ts-order-query-service
        port:
          number: 12032

  - match:
    - uri:
        prefix: /api/v1/order
    route:
    - destination:
        host: ts-order-service
        port:
          number: 12031

  - match:
    - uri:
        prefix: /api/v1/payment
    route:
    - destination:
        host: ts-payment-service
        port:
          number: 19001

  - match:
    - uri:
        prefix: /api/v1/route-plan
    route:
    - destination:
        host: ts-route-plan-service
        port:
          number: 11178

  - match:
    - uri:
        prefix: /api/v1/security
    route:
    - destination:
        host: ts-security-service
        port:
          number: 11188

  - match:
    - uri:
        prefix: /api/v1/sms-notification
    route:
    - destination:
        host: ts-sms-notification-service
        port:
          number: 17854

  - match:
    - uri:
        prefix: /api/v1/station
    route:
    - destination:
        host: ts-station-service
        port:
          number: 12345

  - match:
    - uri:
        prefix: /api/v1/ticket-plan
    route:
    - destination:
        host: ts-ticket-plan-service
        port:
          number: 14322

  - match:
    - uri:
        prefix: /api/v1/ticket-purchase
    route:
    - destination:
        host: ts-ticket-purchase-service
        port:
          number: 14568

  - match:
    - uri:
        prefix: /api/v1/ticket-query
    route:
    - destination:
        host: ts-ticket-query-service
        port:
          number: 12346

  - match:
    - uri:
        prefix: /api/v1/ticket
    route:
    - destination:
        host: ts-ticket-service
        port:
          number: 16579

  - match:
    - uri:
        prefix: /api/v1/train
    route:
    - destination:
        host: ts-train-service
        port:
          number: 14567

  - match:
    - uri:
        prefix: /api/v1/user-notification
    route:
    - destination:
        host: ts-user-notification-service
        port:
          number: 17853

  - match:
    - uri:
        prefix: /api/v1/user
    route:
    - destination:
        host: ts-user-service
        port:
          number: 12342

  - match:
    - uri:
        exact: /api/v1/voucher
    route:
    - destination:
        host: ts-voucher-service
        port:
          number: 16101

  - match:
    - uri:
        prefix: /api/v1/wait-order
    route:
    - destination:
        host: ts-wait-order-service
        port:
          number: 17525
