spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos-0.nacos-headless.default.svc.cluster.local,nacos-1.nacos-headless.default.svc.cluster.local,nacos-2.nacos-headless.default.svc.cluster.local}
  application:
    name: ts-ticket-service
  datasource:
    url: jdbc:mysql://${TICKET_MYSQL_HOST:ts-ticket-mysql}:${TICKET_MYSQL_PORT:3306}/${TICKET_MYSQL_DATABASE:ts-ticket-mysql}?useSSL=false
    username: ${TICKET_MYSQL_USER:root}
    password: ${TICKET_MYSQL_PASSWORD:Abcd1234#}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


# HTTP Server
server:
  port: 16579  # HTTP (Tomcat) port

swagger:
  controllerPackage: price.controller