# coding: utf-8

"""
    Voucher Service API

    API documentation for the Train Ticket Voucher microservice. This service provides an endpoint for retrieving or generating reimbursement vouchers based on order information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Voucher Service API",
    description="API documentation for the Train Ticket Voucher microservice. This service provides an endpoint for retrieving or generating reimbursement vouchers based on order information.",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)
