spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos-0.nacos-headless.default.svc.cluster.local,nacos-1.nacos-headless.default.svc.cluster.local,nacos-2.nacos-headless.default.svc.cluster.local}
  application:
    name: ts-security-service

# HTTP Server
server:
  port: 11188  # HTTP (Tomcat) port

swagger:
  controllerPackage: security.controller
