package edu.fudan.common.client.dto.ticket;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Data transfer object representing price configuration.
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class PriceDto {

    /**
     * Unique identifier generated by the database.
     */
    private String id;

    /**
     * Train type identifier.
     */
    private String trainType;

    /**
     * Route identifier.
     */
    private String routeId;

    /**
     * Base ticket price multiplier.
     */
    private Double basicPriceRate;

    /**
     * First-class ticket price multiplier.
     */
    private Double firstClassPriceRate;
}

